name: "sample pipeline"

on:
    push:
        branches:
            - master
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: 'setup node js'
              uses: actions/setup-node@v4
              with: 
                node-version: '21'
            - name: "clone the repo"
              uses: actions/checkout@v4
              
            - name: "install dependencies"
              run: npm install
            - name: "Run Tests"
              run: npm 
            - name: "Run Build"
              run: npm run build   
